# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 315)
        MainWindow.setMinimumSize(QtCore.QSize(440, 315))
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color:rgb(34, 34, 34);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(83, 83, 83);\n"
"    border-radius: 6.5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(52, 52, 52)\n"
"}\n"
"\n"
"QTableWidget\n"
"{\n"
"background-color:rgb(255, 242, 189);\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section\n"
"{\n"
"background-color:rgb(255, 242, 189);\n"
"border: 1px outset red;\n"
"}\n"
"\n"
"QHeaderView\n"
"{\n"
"background-color:  rgb(83, 83, 83);\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"background-color:  rgb(83, 83, 83);\n"
"color:rgb(255, 242, 189);\n"
"border:1px outset rgb(85, 0, 0);\n"
"border-radius: 3px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addEvent = QtWidgets.QPushButton(self.centralwidget)
        self.addEvent.setMinimumSize(QtCore.QSize(191, 41))
        self.addEvent.setObjectName("addEvent")
        self.verticalLayout.addWidget(self.addEvent)
        self.deleteEvent = QtWidgets.QPushButton(self.centralwidget)
        self.deleteEvent.setMinimumSize(QtCore.QSize(191, 41))
        self.deleteEvent.setObjectName("deleteEvent")
        self.verticalLayout.addWidget(self.deleteEvent)
        self.settings = QtWidgets.QPushButton(self.centralwidget)
        self.settings.setMinimumSize(QtCore.QSize(191, 41))
        self.settings.setObjectName("settings")
        self.verticalLayout.addWidget(self.settings)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Event"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        self.addEvent.setText(_translate("MainWindow", "Добавить новое событие"))
        self.deleteEvent.setText(_translate("MainWindow", "Удалить выбранное событие"))
        self.settings.setText(_translate("MainWindow", "Settings/Настройки"))
