# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(497, 426)
        MainWindow.setMinimumSize(QtCore.QSize(384, 367))
        MainWindow.setStyleSheet("QWidget{\n"
"    font: 8pt \"MS Sans Serif\";\n"
"    background-color: rgb(65, 65, 65);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"}\n"
"\n"
"QTableWidget{\n"
"    color:black;\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"\n"
"QTableWidget:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(False)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 4, 1)
        self.newEvent = QtWidgets.QPushButton(self.centralwidget)
        self.newEvent.setObjectName("newEvent")
        self.gridLayout.addWidget(self.newEvent, 0, 1, 1, 2)
        self.editTime = QtWidgets.QPushButton(self.centralwidget)
        self.editTime.setObjectName("editTime")
        self.gridLayout.addWidget(self.editTime, 1, 1, 1, 1)
        self.editEvent = QtWidgets.QPushButton(self.centralwidget)
        self.editEvent.setObjectName("editEvent")
        self.gridLayout.addWidget(self.editEvent, 1, 2, 1, 1)
        self.deleteEvent = QtWidgets.QPushButton(self.centralwidget)
        self.deleteEvent.setObjectName("deleteEvent")
        self.gridLayout.addWidget(self.deleteEvent, 2, 1, 1, 2)
        self.settings = QtWidgets.QPushButton(self.centralwidget)
        self.settings.setObjectName("settings")
        self.gridLayout.addWidget(self.settings, 3, 1, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Event"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        self.newEvent.setText(_translate("MainWindow", "Add new event"))
        self.editTime.setText(_translate("MainWindow", "Edit time"))
        self.editEvent.setText(_translate("MainWindow", "Edit event"))
        self.deleteEvent.setText(_translate("MainWindow", "Delete event"))
        self.settings.setText(_translate("MainWindow", "Settings/Настройки"))
