# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/alarm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(500, 667)
        MainWindow.setMinimumSize(QtCore.QSize(500, 667))
        MainWindow.setMaximumSize(QtCore.QSize(500, 667))
        MainWindow.setStyleSheet("QWidget{\n"
                                 "    background-color:rgb(34, 34, 34);\n"
                                 "    color:rgb(255, 242, 189);\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(0, 0, 500, 500))
        self.openGLWidget.setObjectName("openGLWidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 500, 481, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name.setFont(font)
        self.name.setStyleSheet("QLabel{\n"
                                "text-align:center;\n"
                                "}\n"
                                "")
        self.name.setTextFormat(QtCore.Qt.AutoText)
        self.name.setWordWrap(False)
        self.name.setObjectName("name")
        self.name.setAlignment(Qt.AlignCenter)
        self.verticalLayout.addWidget(self.name)
        self.times = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.times.setFont(font)
        self.times.setObjectName("times")
        self.times.setAlignment(Qt.AlignCenter)
        self.verticalLayout.addWidget(self.times)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name.setText(_translate("MainWindow", "TextLabel"))
        self.times.setText(_translate("MainWindow", "TextLabel"))
